// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoytMZNzsUee68A0otAm7ADJKxGsX8o0M',
    appId: '1:575649660981:web:c89c337118d38d3bb2317c',
    messagingSenderId: '575649660981',
    projectId: 'food-app--auth',
    authDomain: 'food-app--auth.firebaseapp.com',
    storageBucket: 'food-app--auth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_KvkLkBNm2y4TfRyZOxcKrvdy6-bKmBY',
    appId: '1:575649660981:android:b03d9d2a1c6e0fa9b2317c',
    messagingSenderId: '575649660981',
    projectId: 'food-app--auth',
    storageBucket: 'food-app--auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCP9KehMqZi-YZSmIscC3DyIZLwLYW-E8',
    appId: '1:575649660981:ios:3736090605c9b6efb2317c',
    messagingSenderId: '575649660981',
    projectId: 'food-app--auth',
    storageBucket: 'food-app--auth.firebasestorage.app',
    androidClientId: '575649660981-jiol13j6ll5mtu8g26h3fkfv2hn5f6nf.apps.googleusercontent.com',
    iosClientId: '575649660981-edpkr6j0i4gerce7ipjaqvgvv4hcut7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );

}